version: "3.8"
services:
    nginx:
        image: nginx:1.18.0-alpine
        depends_on:
            - website
            - chat
        ports:
            - "8080:8080" # www
            - "8081:8081" # cdn
        volumes:
            - ./website/static:/www/www.destiny.gg/static
            - ./website/public:/www/www.destiny.gg/public
            - ./docker/nginx-config:/etc/nginx/conf.d
            - ./docker/nginx-certs:/etc/nginx/certs
        profiles:
            - dev
    website:
        build:
            context: .
            dockerfile: ./docker/Dockerfile-website
        depends_on:
            - redis
            - mysql
        volumes:
            - ./website:/www/www.destiny.gg
            - /www/www.destiny.gg/vendor/ # Exclude to avoid overwriting in container.
        profiles:
            - dev
    cron:
        build:
            context: .
            dockerfile: ./docker/Dockerfile-website
        command: ["php", "-f", "./cron/index.php"]
        depends_on:
            - redis
            - mysql
        volumes:
            - ./website:/www/www.destiny.gg
            - /www/www.destiny.gg/vendor/
        profiles:
            - dev
    chat:
        build:
            context: .
            dockerfile: ./docker/Dockerfile-chat
        volumes:
          - ./chat/settings.cfg:/app/settings.cfg
          - ./chat/state.dc:/app/state.dc
        depends_on:
            - redis
            - mysql
        extra_hosts:
            - "host.docker.internal:host-gateway"
        profiles:
            - dev
    redis:
        image: redis:5.0.8-alpine
        volumes:
            - redis_data:/data
        profiles:
            - dev
    mysql:
        image: mariadb:10.3.23
        ports:
            - "3333:3306"
        volumes:
            - mysql_data:/var/lib/mysql
            - ./docker/mysql-config:/etc/mysql/mysql.conf.d
            - ./docker/mysql-scripts:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: AslanIsEvil
            MYSQL_DATABASE: destinygg
            MYSQL_USER: destiny
            MYSQL_PASSWORD: AslanIsEvil
        profiles:
            - dev

    website-test:
        build:
            context: .
            dockerfile: ./docker/Dockerfile-website
        depends_on:
            - mysql-test
        volumes:
            - ./website/lib:/www/www.destiny.gg/lib/
            - ./website/tests:/www/www.destiny.gg/tests/
            - ./website/tmp:/www/www.destiny.gg/tmp/
        command: ["vendor/bin/phpunit", "-c", "tests/phpunit.xml", "tests"]
        profiles:
            - test
    mysql-test:
        image: mariadb:10.3.23
        volumes:
            - mysql_test_data:/var/lib/mysql
            - ./docker/mysql-config:/etc/mysql/mysql.conf.d
            - ./docker/mysql-scripts:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: AslanIsEvil
            MYSQL_DATABASE: destinygg
            MYSQL_USER: destiny
            MYSQL_PASSWORD: AslanIsEvil
        logging:
            driver: none
        profiles:
            - test

volumes:
    mysql_data:
    mysql_test_data:
    redis_data:
