FROM golang:1.15 AS builder

WORKDIR /build

COPY ./chat/go.mod .
COPY ./chat/go.sum .
RUN go mod download
RUN go mod verify

COPY ./chat/*.go ./
RUN go build -o chat .

FROM debian:buster-slim
WORKDIR /app
COPY --from=builder /build/chat .

ENTRYPOINT ["./chat"]
