FROM php:7.4-fpm

WORKDIR /www/www.destiny.gg
COPY docker/php-config/php.ini-development $PHP_INI_DIR/php.ini

RUN apt-get update && apt-get install -y \
    zip \
    git

RUN docker-php-ext-install pdo_mysql

RUN pecl install -o -f redis \
    &&  rm -rf /tmp/pear \
    &&  docker-php-ext-enable redis

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
COPY ./website/composer.json .
RUN composer install

CMD ["php-fpm"]
