FROM node:18.6.0-slim

WORKDIR /build
COPY --from=certs rootCA.pem dgg.crt
COPY . .
RUN npm ci --production=false

ENV NODE_EXTRA_CA_CERTS=dgg.crt

RUN chown -R node:node /build
USER node

CMD ["npm", "start"]
