<?php

//ini_set('log_errors', 1);
//ini_set('error_log', _BASEDIR . '/log/php.log');
//ini_set('error_reporting', E_ALL ^ (E_NOTICE | E_WARNING | E_STRICT | E_DEPRECATED));
//ini_set('date.timezone', 'UTC');

use Destiny\Common\Authentication\AuthProvider;
use Destiny\StreamInfo\StreamPlatform;
use Destiny\Homepage\UploadsClickEvent;
use Monolog\Level;

return [
    'cacheNamespace' => '_web18',
    'crypto' => [                   // the key and seed should be a minimum of 32 random generated bytes
        'key' => 'd4f5db0bdb182c7452cb43ea1dd7b105',   // used as the key for encryption
        'seed' => '8fa14cdd754f91cc6554c9e71929cce7',  // used as the seed for hashing like hmac
    ],

    'deleted_user_hash' => 'c1718b6c2aad27fada8e914458cbc951',
    'allowImpersonation' => true,  // MUST BE OFF ON LIVE AT ALL TIMES. usage: /impersonate?user=Cene or /impersonate?userId=12

    'embed' => [
        'displayName' => 'Broadcaster',
        'twitchParents' => ['localhost'], // Domains that will embed Twitch streams, e.g., 'www.example.com'. See https://discuss.dev.twitch.tv/t/twitch-embedded-player-updates-in-2020/23956 for more details.
        'embedTwitchStream' => true, // Requires the broadcaster to set their channel name in the `twitch` config array.
        'embedYouTubeStream' => false, // Requires the broadcaster to set their channel ID in the `youtubebroadcaster` config array and to authenticate on `/admin/youtube`.
        'embedFacebookStream' => false, // Requires the broadcaster to authenticate on `/admin/facebook`.
        'chat' => '/embed/chat'
    ],

    'broadcasterId' => 1, // User ID of the streamer.
    'origin' => 'https://localhost:8080',
    'production' => false,
    'logLevel' => Level::Debug,
    'chatWebSocketUrl' => 'wss://localhost:8080/ws',
    'apiWebSocketUrl' => 'wss://localhost:8080/ws-api',
    'cdn' => ['domain' => '127.0.0.1:8081','protocol' => 'https://'],
    'blog' => ['feed' => ''],
    'reddit' => ['threads' => ''],
    'android' => ['app' => ''],
    'meta' => [],
    'links' => [],
    'banAppealUrl' => '',
    'support_email' => '',
    'google-verification' => '',
    'googleApiKey' => '',
    'calendar' => '',
    'merch' => [],
    'vodsSource' => StreamPlatform::YouTube,

    'privateKeys' => [
        'reddit' => '',
        'minecraft' => '',
        'chat' => 'aboycalledsuesucks',
        'api' => 'blubstinya',
        'mm' => '',
    ],

    'images' => [
        'path' => _BASEDIR . '/static/cache/',
        'uri' => '/cache',
    ],

    'redis' => [
        'host' => 'localhost',
        'port' => 6379,
        'database' => 0,
        'scriptdir' => _BASEDIR . '/scripts/redis/',
    ],

    'oauth_providers' => [
        'google' => [
            'client_id' => '',
            'client_secret' => '',
        ],
        'youtube' => [
            'client_id' => '',
            'client_secret' => '',
        ],
        'youtubebroadcaster' => [
            'client_id' => '',
            'client_secret' => '',
        ],
        'twitch' => [
            'client_id' => '',
            'client_secret' => '',
            'minimum_account_age_days' => 0
        ],
        'twitter' => [
            'client_id' => '',
            'client_secret' => '',
            'minimum_account_age_days' => 0
        ],
        'reddit' => [
            'client_id' => '',
            'client_secret' => '',
            'minimum_karma' => 0,
            'minimum_account_age_days' => 0
        ],
        'discord' => [
            'client_id' => '',
            'client_secret' => '',
            'minimum_account_age_days' => 0
        ],
        'streamlabs' => [
            'client_id' => '',
            'client_secret' => '',
        ],
        'twitchbroadcaster' => [
            'client_id' => '',
            'client_secret' => '',
        ],
        'streamelements' => [
            'client_id' => '',
            'client_secret' => '',
        ],
        'steam' => [
            'openid_realm' => 'https://localhost:8080',
        ],
        'facebookbroadcaster' => [
            'client_id' => '',
            'client_secret' => '',
        ],
        'vimeo' => [
            'client_id' => '',
            'client_secret' => '',
        ],
        'patreon' => [
            'client_id' => '',
            'client_secret' => '',
        ],
        'patreonbroadcaster' => [
            'webhooks_uri' => 'https://localhost:8080/patreon/webhooks',
        ],
    ],

    'cookie' => [
        'domain' => '',
        'path' => '/',
        'secure' => true,
        'httponly' => true,
        'samesite' => 'none'
    ],

    'db' => [
        'driver'        => 'pdo_mysql',
        'host'          => 'mysql:3306',
        'user'          => 'destiny',
        'dbname'        => 'destinygg',
        'password'      => 'AslanIsEvil',
        'charset'       => 'UTF8',
        'driverOptions' => [PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES UTF8,time_zone = \'+0:00\'']
    ],

    'curl' => ['timeout' => 15, 'connect_timeout' => 7, 'http_errors' => false],

    'paypal' => [
        'environment' => \Destiny\PayPal\PayPalEnvironment::SANDBOX,
        'username' => '',
        'password' => '',
        'signature' => '',
        'endpoint_checkout' => 'https://www.sandbox.paypal.com/webscr?cmd=_express-checkout&token=',
        'endpoint_ipn' => 'http://localhost/ipn/',
    ],

    'youtubebroadcaster' => [
        'sync_memberships' => false,
        'channelId' => '',
    ],

    'analytics' => [
        'account' => '',
        'domainName' => ''
    ],

    'g-recaptcha' => [
        'key' => '',
        'secret' => '',
    ],

    'lastfm' => [
        'apikey' => '',
        'user' => ''
    ],

    'libsyn' => [
        'user' => 'destiny',
    ],

    'amazonTags' => [
        'www.amazon.com' => null,
        'www.amazon.ca' => null,
        'www.amazon.co.uk' => null,
        'www.amazon.de' => null
    ],

    'amazonDisclaimer' => '',

    'twitch' => [
        'id' => 71092938,
        'user' => 'xqc',
        'webhooks_callback' => '',
        'eventsub_secret' => '', // Must be between 10 and 100 characters
        'gqlClientId' => 'kimne78kx3ncx6brgo4mv6wki5h1ko',
    ],

    'discord' => [
        'webhook' => ''
    ],

    'streamelements' => [
        'alert_donations' => true,
        'alert_subscriptions' => true,
        'send_donations' => true,
    ],

    'streamlabs' => [
        'alert_donations' => true,
        'alert_subscriptions' => true,
        'send_donations' => true,
    ],

    'twitchbroadcaster' => [
        'alert_donations' => true,
        'alert_subscriptions' => true,
        'send_donations' => true,
    ],

    'facebookbroadcaster' => [
        'webhookVerifyToken' => '',
        'webhookCallbackUrl' => 'https://localhost/facebook/webhook',
    ],

    'vimeo' => [
        'folder' => '',
    ],

    'subscriptionType' => 'destiny.gg',

    'commerce' => [
        'receiver_email' => '',
        'currency' => 'USD',
        'minimum_donation' => 5,
        'minimum_donation_for_unban' => 5,
        'tiers' => [
            ['tier' => 1, 'tierLabel' => 'Tier I'],
            ['tier' => 2, 'tierLabel' => 'Tier II'],
            ['tier' => 3, 'tierLabel' => 'Tier III'],
            ['tier' => 4, 'tierLabel' => 'Tier IV'],
            ['tier' => 5, 'tierLabel' => 'Tier V'],
        ],
        'subscriptions' => [
            '1-MONTH-SUB' => [
                'id'                => '1-MONTH-SUB',
                'tier'              => 1,
                'tierLabel'         => 'Tier I',
                'itemLabel'         => 'Tier 1 (1 month)',
                'agreement'         => '$5.00 (per month) recurring subscription',
                'amount'            => '5.00',
                'billingFrequency'  => 1,
                'billingPeriod'     => 'Month'
            ],
            '3-MONTH-SUB' => [
                'id'                => '3-MONTH-SUB',
                'tier'              => 1,
                'tierLabel'         => 'Tier I',
                'itemLabel'         => 'Tier 1 (3 month)',
                'agreement'         => '$12.00 (per 3 months) recurring subscription',
                'amount'            => '12.00',
                'billingFrequency'  => 3,
                'billingPeriod'     => 'Month'
            ],
            '1-MONTH-SUB2' => [
                'id'                => '1-MONTH-SUB2',
                'tier'              => 2,
                'tierLabel'         => 'Tier II',
                'itemLabel'         => 'Tier 2 (1 month)',
                'agreement'         => '$10.00 (per month) recurring subscription',
                'amount'            => '10.00',
                'billingFrequency'  => 1,
                'billingPeriod'     => 'Month'
            ],
            '3-MONTH-SUB2' => [
                'id'                => '3-MONTH-SUB2',
                'tier'              => 2,
                'tierLabel'         => 'Tier II',
                'itemLabel'         => 'Tier 2 (3 month)',
                'agreement'         => '$24.00 (per 3 months) recurring subscription',
                'amount'            => '24.00',
                'billingFrequency'  => 3,
                'billingPeriod'     => 'Month'
            ],
            '1-MONTH-SUB3' => [
                'id'                => '1-MONTH-SUB3',
                'tier'              => 3,
                'tierLabel'         => 'Tier III',
                'itemLabel'         => 'Tier 3 (1 month)',
                'agreement'         => '$20.00 (per month) recurring subscription',
                'amount'            => '20.00',
                'billingFrequency'  => 1,
                'billingPeriod'     => 'Month'
            ],
            '3-MONTH-SUB3' => [
                'id'                => '3-MONTH-SUB3',
                'tier'              => 3,
                'tierLabel'         => 'Tier III',
                'itemLabel'         => 'Tier 3 (3 month)',
                'agreement'         => '$48.00 (per 3 months) recurring subscription',
                'amount'            => '48.00',
                'billingFrequency'  => 3,
                'billingPeriod'     => 'Month'
            ],
            '1-MONTH-SUB4' => [
                'id'                => '1-MONTH-SUB4',
                'tier'              => 4,
                'tierLabel'         => 'Tier IV',
                'itemLabel'         => 'Tier 4 (1 month)',
                'agreement'         => '$40.00 (per month) recurring subscription',
                'amount'            => '40.00',
                'billingFrequency'  => 1,
                'billingPeriod'     => 'Month'
            ],
            '3-MONTH-SUB4' => [
                'id'                => '3-MONTH-SUB4',
                'tier'              => 4,
                'tierLabel'         => 'Tier IV',
                'itemLabel'         => 'Tier 4 (3 month)',
                'agreement'         => '$96.00 (per 3 months) recurring subscription',
                'amount'            => '96.00',
                'billingFrequency'  => 3,
                'billingPeriod'     => 'Month'
            ],
            '1-MONTH-SUB5' => [
                'id'                => '1-MONTH-SUB5',
                'tier'              => 5,
                'tierLabel'         => 'Tier V',
                'itemLabel'         => 'Tier 5 (1 month)',
                'agreement'         => '$80.00 (per month) recurring subscription',
                'amount'            => '80.00',
                'billingFrequency'  => 1,
                'billingPeriod'     => 'Month'
            ],
            '3-MONTH-SUB5' => [
                'id'                => '3-MONTH-SUB5',
                'tier'              => 5,
                'tierLabel'         => 'Tier V',
                'itemLabel'         => 'Tier 5 (3 month)',
                'agreement'         => '$192.00 (per 3 months) recurring subscription',
                'amount'            => '192.00',
                'billingFrequency'  => 3,
                'billingPeriod'     => 'Month'
            ],
        ]
    ],

    'iplookupservices' => [
        ['label' => 'iplocation.net', 'url' => 'https://www.iplocation.net/?query={IP_ADDRESS}'],
        ['label' => 'greynoise.io','url' => 'https://viz.greynoise.io/ip/{IP_ADDRESS}'],
        ['label' => 'shodan.io','url' => 'https://www.shodan.io/host/{IP_ADDRESS}'],
        ['label' => 'scamalytics.com','url' => 'https://scamalytics.com/ip/{IP_ADDRESS}'],
    ],

    'online_message' => 'Online! :)',
    'offline_message' => 'Offline... :(',

    'primaryPlatform' => StreamPlatform::Twitch,

    'logsApi' => [
        'mentions' => 'http://localhost:9999/api/v1/mentions/Destinygg/%s.json',
        'stalk' => 'http://localhost:9999/api/v1/stalk/Destinygg/%s.json',
    ],

    'featuredUploads' => [
        'platform'   => StreamPlatform::YouTube,
        'clickEvent' => UploadsClickEvent::Source
    ],

    'manifoldMarketsUserId' => 0,
    'manifoldMarketsReferralUrl' => null,

    'footer' => [
        'copyrightName' => null,
        'contactEmail' => null,
    ],
];
